<?php
require_once "../dbconfig.php";

$data = json_decode(file_get_contents("php://input"), true);

$student_id = $data['student_id'];
$email = $data['email'];
$password = password_hash($data['password'], PASSWORD_DEFAULT);
$first_name = $data['first_name'];
$last_name = $data['last_name'];
$middle_name = $data['middle_name'] ?? '';
$course = $data['course'];

$conn->begin_transaction();

try {
    // 1. Insert into Accounts (Status is 'active' because Admin added this)
    $stmt1 = $conn->prepare("INSERT INTO accounts (user_id, password, email, user_type, account_status) VALUES (?, ?, ?, 'student', 'active')");
    $stmt1->bind_param("sss", $student_id, $password, $email);
    $stmt1->execute();

    // 2. Insert into Students (Initial insert to get UUID and Timestamp)
    $stmt2 = $conn->prepare("INSERT INTO students (student_id, first_name, last_name, middle_name, course) VALUES (?, ?, ?, ?, ?)");
    $stmt2->bind_param("sssss", $student_id, $first_name, $last_name, $middle_name, $course);
    $stmt2->execute();
    
    // 3. Get the data generated by MySQL
    $last_id = $conn->insert_id; // This is the auto-increment UUID
    $res = $conn->query("SELECT uuid, created_at FROM students WHERE uuid = $last_id");
    $row = $res->fetch_assoc();
    
    $uuid = $row['uuid'];
    $created_at = $row['created_at'];

    // 4. Construct your specific QR format: UUID|student_id|last|first|course|timestamp
    $qr_string = "ID:$uuid|SID:$student_id|L:$last_name|F:$first_name|C:$course|TS:$created_at";

    // 5. Update the student record with the final QR data
    $stmt3 = $conn->prepare("UPDATE students SET qr_data = ? WHERE uuid = ?");
    $stmt3->bind_param("si", $qr_string, $uuid);
    $stmt3->execute();

    $conn->commit();
    echo json_encode(["success" => true, "message" => "Student registered with custom QR data"]);

} catch (Exception $e) {
    $conn->rollback();
    echo json_encode(["success" => false, "message" => $e->getMessage()]);
}
?>
