import { useEffect, useState, useMemo } from "react";
import axios from "axios";
import { motion } from "framer-motion";
import { BookOpenIcon } from "lucide-react";
import { API_BASE_URL } from "@/API/APIConfig";

// Components (Fixed space-fragmented file name imports)
import CirculationToolbar from "./components/CirculationToolbar";
import CirculationTable from "./components/CirculationTable";

export interface CirculationLogData {
  loan_id: string;
  student_id: string;
  full_name: string;
  asset_title: string; 
  asset_type: "book" | "research";
  borrow_date: string;
  due_date: string;
  return_date: string | null;
  status: "borrowed" | "returned" | "overdue";
}

const CirculationLog = () => {
  const isoToday = new Date().toISOString().split("T")[0]; // Formats to 'YYYY-MM-DD'
  const [logs, setLogs] = useState<CirculationLogData[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [selectedDate, setSelectedDate] = useState(isoToday);
  const [sortOrder, setSortOrder] = useState<"asc" | "desc">("desc");
  const [loading, setLoading] = useState(true);

  const fetchCirculation = async () => {
    try {
      setLoading(true);
      const response = await axios.get(`${API_BASE_URL}/admin/get_circulation_logs.php`);
      if (Array.isArray(response.data)) {
        setLogs(response.data);
      }
    } catch (error) {
      console.error("Error fetching circulation history logs:", error);
    } finally {
      setLoading(false);
    }
  };

  // Synchronizes live asset mutations across open tabs/windows via BroadcastChannel
  useEffect(() => {
    fetchCirculation();
    const channel = new BroadcastChannel("circulation_sync");
    
    channel.onmessage = (event) => {
      if (event.data?.type === "NEW_CIRCULATION") {
        fetchCirculation();
      }
    };
    
    return () => channel.close();
  }, []);

  // MULTI-KEYWORD SEARCH AND DATE FILTER ENGINE FOR UNIFIED SCHEMAS
  const filteredLogs = useMemo(() => {
    // Formats client calendar states to match the textual style generated by the PHP backend (e.g. "Oct 06, 2026")
    const parsedSelectedDate = new Date(selectedDate).toLocaleDateString("en-US", {
      month: "short",
      day: "2-digit",
      year: "numeric"
    });

    return logs
      .filter((log) => {
        const searchBlob = `
          ${log.full_name || ""} 
          ${log.student_id || ""} 
          ${log.asset_title || ""}
        `.toLowerCase();
        
        const matchesSearch = searchBlob.includes(searchTerm.trim().toLowerCase());
        const matchesDate = log.borrow_date === parsedSelectedDate;
        
        return matchesSearch && matchesDate;
      })
      .sort((a, b) => {
        const timeA = new Date(a.borrow_date).getTime() || 0;
        const timeB = new Date(b.borrow_date).getTime() || 0;
        return sortOrder === "asc" ? timeA - timeB : timeB - timeA;
      });
  }, [logs, searchTerm, selectedDate, sortOrder]);

  return (
    <motion.div
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      className="space-y-6 text-left"
    >
      {/* View Header Branding Segment */}
      <div className="flex items-center gap-3">
        <div className="bg-white p-2 rounded-lg text-cvsu-green-base border border-gray-100 shadow-sm">
          <BookOpenIcon size={24} />
        </div>
        <div>
          <h2 className="text-xl md:text-2xl font-montserrat font-black text-cvsu-green-dark uppercase tracking-tight">
            Book & Manuscript Circulation
          </h2>
          <p className="text-xs text-gray-500">
            Track textbook borrowing and research manuscript log histories across the CEIT Reading Room
          </p>
        </div>
      </div>

      {/* Control Toolbar Hooks */}
      <CirculationToolbar
        searchTerm={searchTerm}
        setSearchTerm={setSearchTerm}
        selectedDate={selectedDate}
        setSelectedDate={setSelectedDate}
        sortOrder={sortOrder}
        setSortOrder={setSortOrder}
      />

      {/* Main Core Render Table Component */}
      <CirculationTable logs={filteredLogs} loading={loading} />
    </motion.div>
  );
};

export default CirculationLog;
